#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

fixedPositions:
  - &fixedPositionsForCentroEmergencia
    group0:
      fields:
        ip: true
        puerto: true
production: 
  main: 
    module: klearMatrix
    defaultScreen: centrosEmergenciaList_screen
  screens: 
    centrosEmergenciaList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *CentrosEmergencia
      title: _("List of %s", ngettext('Centro de emergencia', 'Centros de emergencia', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            centrosEmergenciaEdit_screen: true
            codigoAperturaList_screen: true
          dialogs: 
            centrosEmergenciaDel_dialog: true
          default: centrosEmergenciaEdit_screen
      options: 
        title: _("Options")
        screens: 
          centrosEmergenciaNew_screen: true
    centrosEmergenciaNew_screen: 
      <<: *CentrosEmergencia
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Centro de emergencia', 'Centros  de emergencia', 1))
      fields: 
        order: 
          identificador: true
      fixedPositions:
        <<: *fixedPositionsForCentroEmergencia
    centrosEmergenciaEdit_screen: 
      <<: *CentrosEmergencia
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Centro de emergencia', 'Centros  de emergencia', 1))
      fixedPositions:
        <<: *fixedPositionsForCentroEmergencia
      
    codigoAperturaList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *CodigosApertura
      title: _("Codigos de apertura de %s", '%parent%')
      class: ui-silk-text-allcaps
      filterField: centroEmergenciaId
      parentOptionCustomizer:
        - recordCount
      fields: 
        options: 
          title: _("Options")
          screens: 
            codigoAperturaEdit_screen: false
          dialogs: 
            codigoAperturaDel_dialog: true
          default: codigoAperturaEdit_screen
      options: 
        title: _("Options")
        screens: 
          codigoAperturaNew_screen: false
    codigoAperturaNew_screen: 
      <<: *CodigosApertura
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Codigo de apertura', 'Codigos de apertura', 1))
      filterField: centroEmergenciaId
      fields: 
        blacklist:
          createdOn: true
    codigoAperturaEdit_screen: 
      <<: *CodigosApertura
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Codigo de apertura', 'Codigos de apertura', 1))
      filterField: centroEmergenciaId
      fields:
        blacklist:
          createdOn: true
      
  dialogs: 
    centrosEmergenciaDel_dialog: 
      <<: *CentrosEmergencia
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Centro de emergencia', 'Centros  de emergencia', 1))
      description: _("Do you want to delete this %s?", ngettext('Centro de emergencia', 'Centros  de emergencia', 1))
      
    codigoAperturaDel_dialog: 
      <<: *CodigosApertura
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Codigo de apertura', 'Codigos de apertura', 1))
      description: _("Do you want to delete this %s?", ngettext('Codigo de apertura', 'Codigos de apertura', 1))
testing: 
  _extends: production
development: 
  _extends: production
