#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: codigosPostalesList_screen
  screens: 
    codigosPostalesList_screen: &codigosPostalesList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *CodigosPostales
      title: _("List of %s", ngettext('Código postal', 'Códigos postales', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            codigosPostalesEdit_screen: true
          dialogs: 
            codigosPostalesDel_dialog: true
          default: codigosPostalesEdit_screen
      options: 
        title: _("Options")
        screens: 
          codigosPostalesNew_screen: true
    codigosPostalesNew_screen: &codigosPostalesNew_screenLink 
      <<: *CodigosPostales
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Código postal', 'Códigos postales', 1))
    codigosPostalesEdit_screen: &codigosPostalesEdit_screenLink 
      <<: *CodigosPostales
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Código postal', 'Códigos postales', 1))
  dialogs: 
    codigosPostalesDel_dialog: 
      <<: *CodigosPostales
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Código postal', 'Códigos postales', 1))
      description: _("Do you want to delete this %s?", ngettext('Código postal', 'Códigos postales', 1))
      message: _("%s successfully deleted.", ngettext('Código postal', 'Códigos postales', 1))
testing: 
  _extends: production
development: 
  _extends: production
