#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: codigosAperturaList_screen
  screens: 
    codigosAperturaList_screen: &codigosAperturaList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *CodigosApertura
      title: _("List of %s", ngettext('Codigos apertura', 'Codigos apertura(s)', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            codigosAperturaEdit_screen: false
          dialogs: 
            codigosAperturaDel_dialog: true
          default: codigosAperturaEdit_screen
      options: 
        title: _("Options")
        screens: 
          codigosAperturaNew_screen: false
    codigosAperturaNew_screen: &codigosAperturaNew_screenLink 
      <<: *CodigosApertura
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Codigos apertura', 'Codigos apertura(s)', 1))
      fields: 
        blacklist: 
          fechaLlamada: true
    codigosAperturaEdit_screen: &codigosAperturaEdit_screenLink 
      <<: *CodigosApertura
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Codigos apertura', 'Codigos apertura(s)', 1))
      fields: 
        blacklist: 
          fechaLlamada: true
#        readOnly:
#          fechaLlamada: true
#          contribuyenteId: true
#          codigoApertura: true
#          centroEmergenciaId: true
  dialogs: 
    codigosAperturaDel_dialog: 
      <<: *CodigosApertura
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Codigos apertura', 'Codigos apertura(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Codigos apertura', 'Codigos apertura(s)', 1))
      message: _("%s successfully deleted.", ngettext('Codigos apertura', 'Codigos apertura(s)', 1))
testing: 
  _extends: production
development: 
  _extends: production
