#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: codigoAperturaList_screen
  screens: 
    codigoAperturaList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *CodigoApertura
      title: _("List of %s", ngettext('Codigo apertura', 'Codigo apertura(s)', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            codigoAperturaEdit_screen: true
          dialogs: 
            codigoAperturaDel_dialog: true
          default: codigoAperturaEdit_screen
      options: 
        title: _("Options")
        screens: 
          codigoAperturaNew_screen: true
    codigoAperturaNew_screen: 
      <<: *CodigoApertura
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Codigo apertura', 'Codigo apertura(s)', 1))
    codigoAperturaEdit_screen: 
      <<: *CodigoApertura
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Codigo apertura', 'Codigo apertura(s)', 1))
  dialogs: 
    codigoAperturaDel_dialog: 
      <<: *CodigoApertura
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Codigo apertura', 'Codigo apertura(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Codigo apertura', 'Codigo apertura(s)', 1))
testing: 
  _extends: production
development: 
  _extends: production
