#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: descargasList_screen
  screens: 
    descargasList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *Descargas
      title: _("List of %s", ngettext('Descarga', 'Descargas', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            descargasEdit_screen: true
          dialogs: 
            descargasDel_dialog: true
          default: descargasEdit_screen
      options: 
        title: _("Options")
        screens: 
          descargasNew_screen: true
    descargasNew_screen: 
      <<: *Descargas
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Descarga', 'Descargas', 1))
      fields: 
        blacklist: 
          createdOn: true
    descargasEdit_screen: 
      <<: *Descargas
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Descarga', 'Descargas', 1))
      fields: 
        blacklist: 
          createdOn: true
  dialogs: 
    descargasDel_dialog: 
      <<: *Descargas
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Descarga', 'Descargas', 1))
      description: _("Do you want to delete this %s?", ngettext('Descarga', 'Descargas', 1))
testing: 
  _extends: production
development: 
  _extends: production
