#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: emailsList_screen
  screens: &emailsList_screenTotal 
    emailsList_screen: &emailsList_screenLink 
      controller: list
      pagination:
        items: 25
      <<: *Emails
      title: _("List of %s", ngettext('Email', 'Emails', 0))
      class: ui-silk-email
      filterField: contribuyenteId
      parentOptionCustomizer:
        - recordCount
      fields:
        options:
          title: _("Options")
          screens:
            emailsEdit_screen: true
          dialogs:
            emailsDel_dialog: true
          default: emailsEdit_screen
      options:
        title: _("Options")
        screens:
          emailsNew_screen: true
        dialogs:
          emailsDel_dialog: true
    emailsNew_screen: &emailsNew_screenLink 
      <<: *Emails
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Email', 'Emails', 1))
      filterField: contribuyenteId
      fields:
        blacklist:
          createdOn: true
    emailsEdit_screen: &emailsEdit_screenLink 
      <<: *Emails
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Email', 'Emails', 1))
      filterField: contribuyenteId
      fields:
        blacklist:
          createdOn: true
  dialogs: 
    emailsDel_dialog: &emailsDel_dialogLink 
      <<: *Emails
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Email', 'Emails', 1))
      description: _("Do you want to delete this %s?", ngettext('Email', 'Emails', 1))
      message: _("%s successfully deleted.", ngettext('Email', 'Emails', 1))
      multiItem: 1
      labelOnList: 1

    emailsAddDel_dialog: &emailsAddDel_dialogLink 
      <<: *Emails
      module: default
      controller: klear-contribuyente-email
      action: index
      label: true
      class: ui-silk-email-add
      title: _("Agregar email", '%parent%')
      description: _("Se añadirá una cuenta de correo al contribuyente al que se está editando.")
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
