#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: importadoresList_screen
  screens: 
    importadoresList_screen: &importadoresList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Importadores
      title: _("List of %s", ngettext('Importador', 'Importadores', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            importadoresEdit_screen: false
          dialogs: 
            importadoresDel_dialog: true
          default: importadoresEdit_screen
      options: 
        title: _("Options")
        screens: 
          importadoresNew_screen: true
        dialogs: 
          importadoresDel_dialog: true
    importadoresNew_screen: &importadoresNew_screenLink 
      <<: *Importadores
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Importador', 'Importadores', 1))
    importadoresEdit_screen: &importadoresEdit_screenLink 
      <<: *Importadores
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Importador', 'Importadores', 1))
  dialogs: 
    importadoresDel_dialog: &importadoresDel_screenLink 
      <<: *Importadores
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('MDB', 'MDBs', 1))
      description: _("Do you want to delete this %s?", ngettext('MDB', 'MDBs', 1))
      message: _("%s successfully deleted.", ngettext('MDB', 'MDBs', 1))
      multiItem: 1
      labelOnList: 1

  commands: 
    ArchivoDownload_command: 
      <<: *Importadores
      controller: File
      action: force-download
      mainColumn: archivo
    ArchivoUpload_command: 
      <<: *Importadores
      controller: File
      action: upload
      mainColumn: archivo
    ArchivoPreview_command: 
      <<: *Importadores
      controller: File
      action: preview
      mainColumn: archivo
testing: 
  _extends: production
development: 
  _extends: production
