#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: klearUsersRolesList_screen
  screens: 
    klearUsersRolesList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *KlearUsersRoles
      title: _("List of %s", ngettext('Klear users role', 'Klear users roles', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            klearUsersRolesEdit_screen: true
          dialogs: 
            klearUsersRolesDel_dialog: true
          default: klearUsersRolesEdit_screen
      options: 
        title: _("Options")
        screens: 
          klearUsersRolesNew_screen: true
    klearUsersRolesNew_screen: 
      <<: *KlearUsersRoles
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Klear users role', 'Klear users roles', 1))
    klearUsersRolesEdit_screen: 
      <<: *KlearUsersRoles
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Klear users role', 'Klear users roles', 1))
  dialogs: 
    klearUsersRolesDel_dialog: 
      <<: *KlearUsersRoles
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Klear users role', 'Klear users roles', 1))
      description: _("Do you want to delete this %s?", ngettext('Klear users role', 'Klear users roles', 1))
testing: 
  _extends: production
development: 
  _extends: production
