#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
fixedPositions:
  - &fixedPositionsForKlearUsers
    group0:
      fields:
        login: 1
        email: 2
production: 
  main: 
    module: klearMatrix
    defaultScreen: klearUsersList_screen
  screens: 
    klearUsersList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *KlearUsers
      title: _("List of %s", ngettext('Klear user', 'Klear users', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            klearUsersEdit_screen: true
          dialogs: 
            klearUsersDel_dialog: true
          default: klearUsersEdit_screen
      options: 
        title: _("Options")
        screens: 
          klearUsersNew_screen: true
    klearUsersNew_screen: 
      <<: *KlearUsers
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Klear user', 'Klear users', 1))
      fields: 
        blacklist: 
          updateOn: true
          createdOn: true
      fixedPositions:
        <<: *fixedPositionsForKlearUsers
    klearUsersEdit_screen: 
      <<: *KlearUsers
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Klear user', 'Klear users', 1))
      fields: 
        blacklist: 
          updateOn: true
          createdOn: true
      fixedPositions:
        <<: *fixedPositionsForKlearUsers
  dialogs: 
    klearUsersDel_dialog: 
      <<: *KlearUsers
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Klear user', 'Klear users', 1))
      description: _("Do you want to delete this %s?", ngettext('Klear user', 'Klear users', 1))
testing: 
  _extends: production
development: 
  _extends: production
