#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: klearSectionsList_screen
  screens: 
    klearSectionsList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *KlearSections
      title: _("List of %s", ngettext('Klear section', 'Klear sections', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            klearSectionsEdit_screen: true
          dialogs: 
            klearSectionsDel_dialog: true
          default: klearSectionsEdit_screen
      options: 
        title: _("Options")
        screens: 
          klearSectionsNew_screen: true
    klearSectionsNew_screen: 
      <<: *KlearSections
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Klear section', 'Klear sections', 1))
    klearSectionsEdit_screen: 
      <<: *KlearSections
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Klear section', 'Klear sections', 1))
  dialogs: 
    klearSectionsDel_dialog: 
      <<: *KlearSections
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Klear section', 'Klear sections', 1))
      description: _("Do you want to delete this %s?", ngettext('Klear section', 'Klear sections', 1))
testing: 
  _extends: production
development: 
  _extends: production
