#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: logEmailsList_screen
  screens: 
    logEmailsList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *LogEmails
      title: _("List of %s", ngettext('Log email', 'Log emails', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            logEmailsEdit_screen: true
          dialogs: 
            logEmailsDel_dialog: true
          default: logEmailsEdit_screen
      options: 
        title: _("Options")
        screens: 
          logEmailsNew_screen: true
    logEmailsNew_screen: 
      <<: *LogEmails
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Log email', 'Log emails', 1))
      fields: 
        blacklist: 
          createdOn: true
    logEmailsEdit_screen: 
      <<: *LogEmails
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Log email', 'Log emails', 1))
      fields: 
        blacklist: 
          createdOn: true
  dialogs: 
    logEmailsDel_dialog: 
      <<: *LogEmails
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Log email', 'Log emails', 1))
      description: _("Do you want to delete this %s?", ngettext('Log email', 'Log emails', 1))
testing: 
  _extends: production
development: 
  _extends: production
