#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: marcasPosteList_screen
  screens: 
    marcasPosteList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *MarcasPoste
      title: _("List of %s", ngettext('Marca', 'Marcas', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            marcasPosteEdit_screen: true
          dialogs: 
            marcasPosteDel_dialog: true
          default: marcasPosteEdit_screen
      options: 
        title: _("Options")
        screens: 
          marcasPosteNew_screen: true
    marcasPosteNew_screen: &marcasPosteNew_screenLink 
      <<: *MarcasPoste
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Marca', 'Marcas', 1))
      fields: 
        blacklist: 
          createdOn: true
    marcasPosteEdit_screen: 
      <<: *MarcasPoste
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Marca', 'Marcas', 1))
      fields: 
        blacklist: 
          createdOn: true
  dialogs: 
    marcasPosteDel_dialog: 
      <<: *MarcasPoste
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Marca', 'Marcas', 1))
      description: _("Do you want to delete this %s?", ngettext('Marca', 'Marcas', 1))
testing: 
  _extends: production
development: 
  _extends: production
