#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: marcasDispositivoList_screen
  screens: 
    marcasDispositivoList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *MarcasDispositivo
      title: _("List of %s", ngettext('Marca', 'Marcas', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            marcasDispositivoEdit_screen: true
          dialogs: 
            marcasDispositivoDel_dialog: true
          default: marcasDispositivoEdit_screen
      options: 
        title: _("Options")
        screens: 
          marcasDispositivoNew_screen: true
    marcasDispositivoNew_screen: &marcasDispositivoNew_screenLink 
      <<: *MarcasDispositivo
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Marca', 'Marcas', 1))
      fields: 
        blacklist: 
          createdOn: true
    marcasDispositivoEdit_screen: 
      <<: *MarcasDispositivo
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Marca', 'Marcas', 1))
      fields: 
        blacklist: 
          createdOn: true
  dialogs: 
    marcasDispositivoDel_dialog: 
      <<: *MarcasDispositivo
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Marca', 'Marcas', 1))
      description: _("Do you want to delete this %s?", ngettext('Marca', 'Marcas', 1))
testing: 
  _extends: production
development: 
  _extends: production
