#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
fixedPositions:
  - &fixedPositionsForMunicipios
    group0:
      label: _('Audio Español')
      fields:
        esLoc: true
        esLocCodificado: true
    group1:
      label: _('Audio Euskera')
      fields:
        euLoc: true
        euLocCodificado: true
production: 
  main: 
    module: klearMatrix
    defaultScreen: municipiosList_screen
  screens: 
    municipiosList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *Municipios
      title: _("List of %s", ngettext('Municipio', 'Municipios', 0))
      filterClass: Atezatelib_Filtros_FilterMunicipiosCentroEmergencia
      order:
        field: municipio
      fields: 
        order: 
          municipio: true 
          MunicipiosRelCodigosPostales: true
        options: 
          title: _("Options")
          screens: 
            municipiosEdit_screen: true
          dialogs: 
            municipiosDel_dialog: false
          default: municipiosEdit_screen
        blacklist:
          createdOn: true
          MunicipiosRelCercaniaByMunicipio: true
          esLoc: true
          esLocCodificado: true
          euLoc: true
          euLocCodificado: true
      options: 
        title: _("Options")
        screens: 
          municipiosNew_screen: false
      info:
        type: box
        position: left
        icon: help
        label: _("¿Necesitas ayuda?")
        text: _("Aquí se lista solo los Municipios que tengan una relación con un Centro de Emergencia.")
    municipiosNew_screen: 
      <<: *Municipios
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Municipio', 'Municipios', 1))
      fields:
        blacklist:
          createdOn: true
          municipio: true
          estado: true
          MunicipiosRelCodigosPostales: true
      fixedPositions:
        <<: *fixedPositionsForMunicipios
    municipiosEdit_screen: 
      <<: *Municipios
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("%s %s", ngettext('Municipio', 'Municipios', 1),'%parent%')
      fields:
        order:
          municipio: true
        blacklist:
          createdOn: true
          estado: true
          MunicipiosRelCodigosPostales: true
      fixedPositions:
        <<: *fixedPositionsForMunicipios
      info:
        type: box
        position: left
        icon: help
        label: _("¿Necesitas ayuda?")
        text: _("En relación de cercanías, se listan solo los municipios que tienen relación con un contribuyente. De esta manera indicamos que Centros de Emergencia se encuentran disponible para el contribuyente por su zona.")
        
    codigosPostalesNew_screen: &codigosPostalesNew_screenLink 
      <<: *CodigosPostales
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Código postal', 'Códigos postales', 1))
    codigosPostalesEdit_screen: &codigosPostalesEdit_screenLink 
      <<: *CodigosPostales
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Código postal', 'Códigos postales', 1))
         
  dialogs: 
    municipiosDel_dialog: 
      <<: *Municipios
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Municipio', 'Municipios', 1))
      description: _("Do you want to delete this %s?", ngettext('Municipio', 'Municipios', 1))
    codigosPostalesDel_dialog: 
      <<: *CodigosPostales
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Código postal', 'Códigos postales', 1))
      description: _("Do you want to delete this %s?", ngettext('Código postal', 'Códigos postales', 1))
      message: _("%s successfully deleted.", ngettext('Código postal', 'Códigos postales', 1))
  commands: 
    EsLocDownload_command: 
      <<: *Municipios
      controller: File
      action: force-download
      mainColumn: esLoc
    EsLocUpload_command: 
      <<: *Municipios
      controller: File
      action: upload
      mainColumn: esLoc
    EsLocPreview_command: 
      <<: *Municipios
      controller: File
      action: preview
      mainColumn: esLoc
    EuLocDownload_command: 
      <<: *Municipios
      controller: File
      action: force-download
      mainColumn: euLoc
    EuLocUpload_command: 
      <<: *Municipios
      controller: File
      action: upload
      mainColumn: euLoc
    EuLocPreview_command: 
      <<: *Municipios
      controller: File
      action: preview
      mainColumn: euLoc
    EsLocCodificadoDownload_command: 
      <<: *Municipios
      controller: File
      action: force-download
      mainColumn: esLocCodificado
    EsLocCodificadoUpload_command: 
      <<: *Municipios
      controller: File
      action: upload
      mainColumn: esLocCodificado
    EsLocCodificadoPreview_command: 
      <<: *Municipios
      controller: File
      action: preview
      mainColumn: esLocCodificado
    EuLocCodificadoDownload_command: 
      <<: *Municipios
      controller: File
      action: force-download
      mainColumn: euLocCodificado
    EuLocCodificadoUpload_command: 
      <<: *Municipios
      controller: File
      action: upload
      mainColumn: euLocCodificado
    EuLocCodificadoPreview_command: 
      <<: *Municipios
      controller: File
      action: preview
      mainColumn: euLocCodificado
testing: 
  _extends: production
development: 
  _extends: production
