#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: municipiosRelCodigosPostalesList_screen
  screens: 
    municipiosRelCodigosPostalesList_screen: &municipiosRelCodigosPostalesList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *MunicipiosRelCodigosPostales
      title: _("List of %s", ngettext('Municipios rel codigos postale', 'Municipios rel codigos postales', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            municipiosRelCodigosPostalesEdit_screen: true
          dialogs: 
            municipiosRelCodigosPostalesDel_dialog: true
          default: municipiosRelCodigosPostalesEdit_screen
      options: 
        title: _("Options")
        screens: 
          municipiosRelCodigosPostalesNew_screen: true
    municipiosRelCodigosPostalesNew_screen: &municipiosRelCodigosPostalesNew_screenLink 
      <<: *MunicipiosRelCodigosPostales
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Municipios rel codigos postale', 'Municipios rel codigos postales', 1))
    municipiosRelCodigosPostalesEdit_screen: &municipiosRelCodigosPostalesEdit_screenLink 
      <<: *MunicipiosRelCodigosPostales
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Municipios rel codigos postale', 'Municipios rel codigos postales', 1))
  dialogs: 
    municipiosRelCodigosPostalesDel_dialog: 
      <<: *MunicipiosRelCodigosPostales
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Municipios rel codigos postale', 'Municipios rel codigos postales', 1))
      description: _("Do you want to delete this %s?", ngettext('Municipios rel codigos postale', 'Municipios rel codigos postales', 1))
      message: _("%s successfully deleted.", ngettext('Municipios rel codigos postale', 'Municipios rel codigos postales', 1))
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
