#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: municipiosRelCercaniaList_screen
  screens: 
    municipiosRelCercaniaList_screen: &municipiosRelCercaniaList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *MunicipiosRelCercania
      title: _("List of %s", ngettext('Municipios rel cercania', 'Municipios rel cercania(s)', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            municipiosRelCercaniaEdit_screen: true
          dialogs: 
            municipiosRelCercaniaDel_dialog: true
          default: municipiosRelCercaniaEdit_screen
      options: 
        title: _("Options")
        screens: 
          municipiosRelCercaniaNew_screen: true
    municipiosRelCercaniaNew_screen: &municipiosRelCercaniaNew_screenLink 
      <<: *MunicipiosRelCercania
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Municipios rel cercania', 'Municipios rel cercania(s)', 1))
    municipiosRelCercaniaEdit_screen: &municipiosRelCercaniaEdit_screenLink 
      <<: *MunicipiosRelCercania
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Municipios rel cercania', 'Municipios rel cercania(s)', 1))
  dialogs: 
    municipiosRelCercaniaDel_dialog: 
      <<: *MunicipiosRelCercania
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Municipios rel cercania', 'Municipios rel cercania(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Municipios rel cercania', 'Municipios rel cercania(s)', 1))
      message: _("%s successfully deleted.", ngettext('Municipios rel cercania', 'Municipios rel cercania(s)', 1))
testing: 
  _extends: production
development: 
  _extends: production
