#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include RolesList.yaml

fixedPositions:
  - &fixedPositionsForOperarios
    group0:
      fields:
        nombre: true
        rolId: true
production: 
  main: 
    module: klearMatrix
    defaultScreen: operariosList_screen
  screens: 
    operariosList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *Operarios
      title: _("List of %s", ngettext('Operario', 'Operarios', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            operariosEdit_screen: true
          dialogs: 
            operariosDel_dialog: true
          default: operariosEdit_screen
      options: 
        title: _("Options")
        screens: 
          operariosNew_screen: true
    operariosNew_screen: 
      <<: *Operarios
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Operario', 'Operarios', 1))
      fixedPositions:
        <<: *fixedPositionsForOperarios
    operariosEdit_screen: 
      <<: *Operarios
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Operario', 'Operarios', 1))
      fixedPositions:
        <<: *fixedPositionsForOperarios
        
    rolesNew_screen:
      <<: *rolesNew_screenLink 
      
  dialogs: 
    operariosDel_dialog: 
      <<: *Operarios
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Operario', 'Operarios', 1))
      description: _("Do you want to delete this %s?", ngettext('Operario', 'Operarios', 1))
testing: 
  _extends: production
development: 
  _extends: production
