#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: paradasList_screen
  screens: 
    paradasList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *Paradas
      title: _("List of %s", ngettext('Parada', 'Paradas', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            paradasEdit_screen: true
          dialogs: 
            paradasDel_dialog: true
          default: paradasEdit_screen
      options: 
        title: _("Options")
        screens: 
          paradasNew_screen: true
    paradasNew_screen: 
      <<: *Paradas
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Parada', 'Paradas', 1))
    paradasEdit_screen: 
      <<: *Paradas
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Parada', 'Paradas', 1))
  dialogs: 
    paradasDel_dialog: 
      <<: *Paradas
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Parada', 'Paradas', 1))
      description: _("Do you want to delete this %s?", ngettext('Parada', 'Paradas', 1))
testing: 
  _extends: production
development: 
  _extends: production
