#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
fixedPositions:
  - &fixedPositionsForPlantillas
    group0:
      label: _('Audio Español')
      fields:
        esLoc: true
        esLocCodificado: true
    group1:
      label: _('Audio Euskera')
      fields:
        euLoc: true
        euLocCodificado: true
production: 
  main: 
    module: klearMatrix
    defaultScreen: plantillasTelefonoList_screen
  screens: 
    plantillasTelefonoList_screen: &plantillasTelefonoList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *PlantillasTelefono
      title: _("List of %s", ngettext('Plantillas telefono', 'Plantillas telefono(s)', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            plantillasTelefonoEdit_screen: true
          dialogs: 
            plantillasTelefonoDel_dialog: true
          default: plantillasTelefonoEdit_screen
        blacklist:
          esLoc: true
          euLoc: true
          esLocCodificado: true
          euLocCodificado: true
      options: 
        title: _("Options")
        screens: 
          plantillasTelefonoNew_screen: true
    plantillasTelefonoNew_screen: &plantillasTelefonoNew_screenLink 
      <<: *PlantillasTelefono
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Plantillas telefono', 'Plantillas telefono(s)', 1))
      fields:
        order:
          asunto: true
        blacklist:
          estado: true
      fixedPositions:
        <<: *fixedPositionsForPlantillas
    plantillasTelefonoEdit_screen: &plantillasTelefonoEdit_screenLink 
      <<: *PlantillasTelefono
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Plantillas telefono', 'Plantillas telefono(s)', 1))
      fields:
        order:
          asunto: true
        blacklist:
          estado: true
      fixedPositions:
        <<: *fixedPositionsForPlantillas
  dialogs: 
    plantillasTelefonoDel_dialog: 
      <<: *PlantillasTelefono
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Plantillas telefono', 'Plantillas telefono(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Plantillas telefono', 'Plantillas telefono(s)', 1))
      message: _("%s successfully deleted.", ngettext('Plantillas telefono', 'Plantillas telefono(s)', 1))
  commands: 
    EsLocDownload_command: 
      <<: *PlantillasTelefono
      controller: File
      action: force-download
      mainColumn: esLoc
    EsLocUpload_command: 
      <<: *PlantillasTelefono
      controller: File
      action: upload
      mainColumn: esLoc
    EsLocPreview_command: 
      <<: *PlantillasTelefono
      controller: File
      action: preview
      mainColumn: esLoc
    EsLocCodificadoDownload_command: 
      <<: *PlantillasTelefono
      controller: File
      action: force-download
      mainColumn: esLocCodificado
    EsLocCodificadoUpload_command: 
      <<: *PlantillasTelefono
      controller: File
      action: upload
      mainColumn: esLocCodificado
    EsLocCodificadoPreview_command: 
      <<: *PlantillasTelefono
      controller: File
      action: preview
      mainColumn: esLocCodificado
    EuLocDownload_command: 
      <<: *PlantillasTelefono
      controller: File
      action: force-download
      mainColumn: euLoc
    EuLocUpload_command: 
      <<: *PlantillasTelefono
      controller: File
      action: upload
      mainColumn: euLoc
    EuLocPreview_command: 
      <<: *PlantillasTelefono
      controller: File
      action: preview
      mainColumn: euLoc
    EuLocCodificadoDownload_command: 
      <<: *PlantillasTelefono
      controller: File
      action: force-download
      mainColumn: euLocCodificado
    EuLocCodificadoUpload_command: 
      <<: *PlantillasTelefono
      controller: File
      action: upload
      mainColumn: euLocCodificado
    EuLocCodificadoPreview_command: 
      <<: *PlantillasTelefono
      controller: File
      action: preview
      mainColumn: euLocCodificado
testing: 
  _extends: production
development: 
  _extends: production
