#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: plantillasEmailList_screen
  screens: 
    plantillasEmailList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *PlantillasEmail
      title: _("List of %s", ngettext('Plantilla email', 'Plantillas email', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            plantillasEmailEdit_screen: true
          dialogs: 
            plantillasEmailDel_dialog: true
          default: plantillasEmailEdit_screen
      options: 
        title: _("Options")
        screens: 
          plantillasEmailNew_screen: true
    plantillasEmailNew_screen: 
      <<: *PlantillasEmail
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Plantilla email', 'Plantillas email', 1))
    plantillasEmailEdit_screen: 
      <<: *PlantillasEmail
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Plantilla email', 'Plantillas email', 1))
  dialogs: 
    plantillasEmailDel_dialog: 
      <<: *PlantillasEmail
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Plantilla email', 'Plantillas email', 1))
      description: _("Do you want to delete this %s?", ngettext('Plantilla email', 'Plantillas email', 1))
testing: 
  _extends: production
development: 
  _extends: production
