#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include MarcasPosteList.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: postesTiposList_screen
  screens: 
    postesTiposList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *PostesTipos
      title: _("List of %s", ngettext('Tipo de poste', 'Tipos de poste', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            postesTiposEdit_screen: true
          dialogs: 
            postesTiposDel_dialog: true
          default: postesTiposEdit_screen
      options: 
        title: _("Options")
        screens: 
          postesTiposNew_screen: true
    postesTiposNew_screen: &postesTiposNew_screenLink 
      <<: *PostesTipos
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Tipo de poste', 'Tipos de poste', 1))
    postesTiposEdit_screen: 
      <<: *PostesTipos
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Tipo de poste', 'Tipos de poste', 1))

    marcaPosteNew_screen: 
      <<: *marcasPosteNew_screenLink 

  dialogs: 
    postesTiposDel_dialog: 
      <<: *PostesTipos
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Tipo de poste', 'Tipos de poste', 1))
      description: _("Do you want to delete this %s?", ngettext('Tipo de poste', 'Tipos de poste', 1))
testing: 
  _extends: production
development: 
  _extends: production
