#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include PostesTiposList.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: postesList_screen
  screens: 
    postesList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *Postes
      title: _("List of %s", ngettext('Poste', 'Postes', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            postesEdit_screen: true
            incidenciasPostesList_screen: true
            cubosList_screen: true
          dialogs: 
            postesDel_dialog: true
          default: postesEdit_screen
        blacklist:
          intuitivo: true
      options: 
        title: _("Options")
        screens: 
          postesNew_screen: true
          importadoresList_screen: true
    postesNew_screen: 
      <<: *Postes
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Poste', 'Postes', 1))
    postesEdit_screen: 
      <<: *Postes
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Poste', 'Postes', 1))
      
    importadoresList_screen: &importadoresList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Importadores
      title: _("Importador")
      label: true
      class: ui-silk-arrow-up
      forcedValues:
        tipo: poste
      fields: 
        options: 
          title: _("Options")
          screens: 
            importadoresEdit_screen: false
          dialogs: 
            importadoresDel_dialog: true
          default: importadoresEdit_screen
      options: 
        title: _("Options")
        screens: 
          importadoresNew_screen: true
      info:
        type: box
        position: left
        icon: help
        text: _("La tabla de datos debe llamarse Contribuyentes y tiene que tener los campos en el siguiente orden, sin importar el nombre definido. idContribuyenteUsoa, nombre, municipioId, createdOn, nif, cuenta, intuitivo, codigoCalle, direccion, portal, bis, escalera, piso, mano, otrosDomicilio, tarifa, cantidad, direccionFiscal, portalFiscal, bisFiscal, escaleraFiscal, pisoFiscal, manoFiscal, localidadFiscal, pkFiscal, provinciaFiscal. Cualquier cambio de formato, hablar con el desarrolador.")
        label: _("Requisitos fichero .mdb")
    importadoresNew_screen: &importadoresNew_screenLink 
      <<: *Importadores
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Importar %s", ngettext('Fichero', 'Ficheros', 1))
      fields:
        blacklist:
          estado: pendiente
      forcedValues:
        tipo: poste
      info:
        type: box
        position: left
        icon: help
        text: _("La tabla de datos debe llamarse Contribuyentes y tiene que tener los campos en el siguiente orden, sin importar el nombre definido. idContribuyenteUsoa, nombre, municipioId, createdOn, nif, cuenta, intuitivo, codigoCalle, direccion, portal, bis, escalera, piso, mano, otrosDomicilio, tarifa, cantidad, direccionFiscal, portalFiscal, bisFiscal, escaleraFiscal, pisoFiscal, manoFiscal, localidadFiscal, pkFiscal, provinciaFiscal. Cualquier cambio de formato, hablar con el desarrollador.")
        label: _("Requisitos fichero .mdb")
        
    postesTiposNew_screen:
      <<: *postesTiposNew_screenLink 
      
    cubosList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *Cubos
      title: _("List of %s", ngettext('Cubo', 'Cubos', 0))
      class: ui-silk-database
      filterField:  posteId
      parentOptionCustomizer:
        - recordCount
      fields: 
        options: 
          title: _("Options")
          screens: 
            incidenciasCubosList_screen: true
            cubosEdit_screen: true
      options: 
        title: _("Options")
        screens: 
          cubosNew_screen: true
          
    cubosNew_screen: 
      <<: *Cubos
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Cubo', 'Cubos', 1))
    cubosEdit_screen: 
      <<: *Cubos
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Cubo', 'Cubos', 1))
      
    cubosTiposNew_screen: &cubosTiposNew_screenLink 
      <<: *CubosTipos
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Tipo de cubo', 'Tipos de cubo', 1))
        
    incidenciasCubosList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *Incidencias
      title: _("List of %s", ngettext('Incidencia', 'Incidencias', 0))
      class: ui-silk-error
      filterField: cuboId
      parentOptionCustomizer:
        - recordCount
      fields: 
        options: 
          title: _("Options")
          screens: 
            incidenciasCubosEdit_screen: true
          dialogs: 
            incidenciasCubosDel_dialog: true
          default: incidenciasCubosEdit_screen
        blacklist:
          createdOn: true
          postesId: true
      options: 
        title: _("Options")
        screens: 
          incidenciasCubosNew_screen: true
    incidenciasCubosNew_screen: 
      <<: *Incidencias
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Incidencia', 'Incidencias', 1))
      filterField: cuboId
      fields:
        blacklist:
          createdOn: true
          postesId: true
    incidenciasCubosEdit_screen: 
      <<: *Incidencias
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Incidencia', 'Incidencias', 1))
      filterField: cuboId
      fields:
        blacklist:
          createdOn: true
          postesId: true

    incidenciasPostesList_screen: 
      controller: list
      preconfiguredFilters:
        pendientes:
          title: "Pendientes"
          field: solucionada
          value: 'no'
        solucionadas:
          title: "Solucionadas"
          field: solucionada
          value: 'si'
      pagination: 
        items: 25
      <<: *Incidencias
      title: _("List of %s", ngettext('Incidencia de Poste', 'Incidencias de Postes', 0))
      class: ui-silk-error
      fields: 
        options: 
          title: _("Options")
          screens: 
            incidenciasPostesEdit_screen: true
          dialogs: 
            incidenciasPostesDel_dialog: true
          default: incidenciasEdit_screen
        blacklist:
          tipoId: true
          createdOn: true
          compostadorId: true
          cuboId: true
          contribuyenteId: true
          puntoRecogidaId: true
          camionId: true
          fieldFakeCubo: true
          fieldFakeCamion: true
          fieldFakeCompostador: true
          fieldFakeContribuyente: true
          fieldFakePostes: true
          fieldFakePuntosRecogida: true
          observacionSolucion: true
          observaciones: true
          entidadDato: true
      options: 
        title: _("Options")
        screens: 
          incidenciasPostesNew_screen: true
      forcedValues: 
        entidad: poste

    incidenciasPostesNew_screen: 
      <<: *Incidencias
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Incidencia', 'Incidencias', 1))
      filterField: postesId
      fields:
        blacklist:
          createdOn: true
          cuboId: true
          compostadorId: true
      forcedValues: 
        entidad: poste
    incidenciasPostesEdit_screen: 
      <<: *Incidencias
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Incidencia', 'Incidencias', 1))
      filterField: postesId
      fields:
        blacklist:
          createdOn: true
          cuboId: true
          compostadorId: true
      forcedValues: 
        entidad: poste
  dialogs: 
    postesDel_dialog: 
      <<: *Postes
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Poste', 'Postes', 1))
      description: _("Do you want to delete this %s?", ngettext('Poste', 'Postes', 1))
      
    importadoresDel_dialog: 
      <<: *Importadores
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Importador', 'Importadores', 1))
      description: _("Do you want to delete this %s?", ngettext('Importador', 'Importadores', 1))
      message: _("%s successfully deleted.", ngettext('Importador', 'Importadores', 1))
      
    cubosDel_dialog: 
      <<: *Cubos
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Cubo', 'Cubos', 1))
      description: _("Do you want to delete this %s?", ngettext('Cubo', 'Cubos', 1))
      
    incidenciasCubosDel_dialog: 
      <<: *Incidencias
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Incidencia', 'Incidencias', 1))
      description: _("Do you want to delete this %s?", ngettext('Incidencia', 'Incidencias', 1))
      
    incidenciasPostesDel_dialog: 
      <<: *Incidencias
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Incidencia', 'Incidencias', 1))
      description: _("Do you want to delete this %s?", ngettext('Incidencia', 'Incidencias', 1))
      
  commands:
    autocomplete_command:
      <<: *Cubos
      controller: field-decorator
      action: index
      autocomplete:
        mapperName: \Atezate\Mapper\Sql\Contribuyentes
        label: nif
        limit: 8
    ArchivoDownload_command: 
      <<: *Importadores
      controller: File
      action: force-download
      mainColumn: archivo
    ArchivoUpload_command: 
      <<: *Importadores
      controller: File
      action: upload
      mainColumn: archivo
    ArchivoPreview_command: 
      <<: *Importadores
      controller: File
      action: preview
      mainColumn: archivo      
testing: 
  _extends: production
development: 
  _extends: production
