#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

fixedPositions:
  - &fixedPositionsForDescargas
    group0:
      fields:
        posicionLat: 1
        posicionLng: 1

production: 
  main: 
    module: klearMatrix
    defaultScreen: puntosDescargaList_screen
  screens: 

    puntosDescargaList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *PuntosDescarga
      title: _("List of %s", ngettext('Puntos descarga', 'Puntos descarga(s)', 0))
      fields: 
        blacklist:
          posicion: true
          posicionLat: true
          posicionLng: true
        options: 
          title: _("Options")
          screens: 
            puntosDescargaEdit_screen: true
          dialogs: 
            puntosDescargaDel_dialog: true
          default: puntosDescargaEdit_screen
      options: 
        title: _("Options")
        screens: 
          puntosDescargaNew_screen: true

    puntosDescargaNew_screen: 
      <<: *PuntosDescarga
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Puntos descarga', 'Puntos descarga(s)', 1))
      fixedPositions:
        <<: *fixedPositionsForDescargas
      fields:
        blacklist:
          posicion: true
          posicionLat: true
          posicionLng: true

    puntosDescargaEdit_screen: 
      <<: *PuntosDescarga
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Puntos descarga', 'Puntos descarga(s)', 1))
      fixedPositions:
        <<: *fixedPositionsForDescargas
      fields:
        blacklist:
          posicion: true
          posicionLat: true
          posicionLng: true

  dialogs: 
    puntosDescargaDel_dialog: 
      <<: *PuntosDescarga
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Puntos descarga', 'Puntos descarga(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Puntos descarga', 'Puntos descarga(s)', 1))
testing: 
  _extends: production
development: 
  _extends: production
