#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: recogidaTiposList_screen
  screens: 
    recogidaTiposList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *RecogidaTipos
      title: _("List of %s", ngettext('Tipo de recogida', 'Tipos de recogida', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            recogidaTiposEdit_screen: true
          dialogs: 
            recogidaTiposDel_dialog: true
          default: recogidaTiposEdit_screen
      options: 
        title: _("Options")
        screens: 
          recogidaTiposNew_screen: true
    recogidaTiposNew_screen: 
      <<: *RecogidaTipos
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Recogida tipo', 'Recogida tipos', 1))
    recogidaTiposEdit_screen: 
      <<: *RecogidaTipos
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Recogida tipo', 'Recogida tipos', 1))
  dialogs: 
    recogidaTiposDel_dialog: 
      <<: *RecogidaTipos
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Recogida tipo', 'Recogida tipos', 1))
      description: _("Do you want to delete this %s?", ngettext('Recogida tipo', 'Recogida tipos', 1))
testing: 
  _extends: production
development: 
  _extends: production
