#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: residuosTiposList_screen
  screens: 
    residuosTiposList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *ResiduosTipos
      title: _("List of %s", ngettext('Tipo de residuos', 'Tipos de residuos', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            residuosTiposEdit_screen: true
          dialogs: 
            residuosTiposDel_dialog: true
          default: residuosTiposEdit_screen
      options: 
        title: _("Options")
        screens: 
          residuosTiposNew_screen: true
    residuosTiposNew_screen: 
      <<: *ResiduosTipos
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Residuos tipo', 'Residuos tipos', 1))
    residuosTiposEdit_screen: 
      <<: *ResiduosTipos
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Residuos tipo', 'Residuos tipos', 1))
  dialogs: 
    residuosTiposDel_dialog: 
      <<: *ResiduosTipos
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Residuos tipo', 'Residuos tipos', 1))
      description: _("Do you want to delete this %s?", ngettext('Residuos tipo', 'Residuos tipos', 1))
testing: 
  _extends: production
development: 
  _extends: production
