#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: revisionTiposList_screen
  screens: 
    revisionTiposList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *RevisionTipos
      title: _("List of %s", ngettext('Tipo de revisión', 'Tipos de revisión', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            revisionTiposEdit_screen: true
          dialogs: 
            revisionTiposDel_dialog: true
          default: revisionTiposEdit_screen
      options: 
        title: _("Options")
        screens: 
          revisionTiposNew_screen: true
    revisionTiposNew_screen: &revisionTiposNew_screenLink 
      <<: *RevisionTipos
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Tipo de revisión', 'Tipos de revisión', 1))
    revisionTiposEdit_screen: 
      <<: *RevisionTipos
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Tipo de revisión', 'Tipos de revisión', 1))
  dialogs: 
    revisionTiposDel_dialog: 
      <<: *RevisionTipos
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Tipo de revisión', 'Tipos de revisión', 1))
      description: _("Do you want to delete this %s?", ngettext('Tipo de revisión', 'Tipos de revisión', 1))
testing: 
  _extends: production
development: 
  _extends: production
