#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include RevisionTiposList.yaml

fixedPositions:
  - &fixedPositionsForRevision
    group0:
      fields:
        compostadoresId: true
        fechaHora: true
        operadorId: true
        revisionTipoId: true
production: 
  main: 
    module: klearMatrix
    defaultScreen: revisionList_screen
  screens: 
    revisionList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *Revision
      title: _("List of %s", ngettext('Revisión', 'Revisiones', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            revisionEdit_screen: true
          dialogs: 
            revisionDel_dialog: true
          default: revisionEdit_screen
      options: 
        title: _("Options")
        screens: 
          revisionNew_screen: true
    revisionNew_screen: 
      <<: *Revision
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Revisión', 'Revisiones', 1))
      fullWidth: true
      fixedPositions:
        <<: *fixedPositionsForRevision
    revisionEdit_screen: 
      <<: *Revision
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Revisión', 'Revisiones', 1))
      fullWidth: true
      fixedPositions:
        <<: *fixedPositionsForRevision
        
    revisionTiposNew_screen:
      <<: *revisionTiposNew_screenLink 
  dialogs: 
    revisionDel_dialog: 
      <<: *Revision
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Revisión', 'Revisiones', 1))
      description: _("Do you want to delete this %s?", ngettext('Revisión', 'Revisiones', 1))
testing: 
  _extends: production
development: 
  _extends: production
