#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: rolesList_screen
  screens: 
    rolesList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *Roles
      title: _("List of %s", ngettext('Rol', 'Roles', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            rolesEdit_screen: true
          dialogs: 
            rolesDel_dialog: true
          default: rolesEdit_screen
      options: 
        title: _("Options")
        screens: 
          rolesNew_screen: true
    rolesNew_screen: &rolesNew_screenLink 
      <<: *Roles
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Rol', 'Roles', 1))
    rolesEdit_screen: 
      <<: *Roles
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Rol', 'Roles', 1))
  dialogs: 
    rolesDel_dialog: 
      <<: *Roles
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Rol', 'Roles', 1))
      description: _("Do you want to delete this %s?", ngettext('Rol', 'Roles', 1))
testing: 
  _extends: production
development: 
  _extends: production
