#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: rutasTiposList_screen
  screens: 
    rutasTiposList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *RutasTipos
      title: _("List of %s", ngettext('Tipo de ruta', 'Tipos de ruta', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            rutasTiposEdit_screen: true
          dialogs: 
            rutasTiposDel_dialog: true
          default: rutasTiposEdit_screen
      options: 
        title: _("Options")
        screens: 
          rutasTiposNew_screen: true
    rutasTiposNew_screen: &rutasNew_screenLink 
      <<: *RutasTipos
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Tipo de ruta', 'Tipos de ruta', 1))
    rutasTiposEdit_screen: 
      <<: *RutasTipos
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Tipo de ruta', 'Tipos de ruta', 1))
  dialogs: 
    rutasTiposDel_dialog: 
      <<: *RutasTipos
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Tipo de ruta', 'Tipos de ruta', 1))
      description: _("Do you want to delete this %s?", ngettext('Tipo de ruta', 'Tipos de ruta', 1))
testing: 
  _extends: production
development: 
  _extends: production
