#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: telefonosList_screen
  screens: &telefonosList_screenTotal
    telefonosList_screen: &telefonosList_screenLink 
      controller: list
      pagination:
        items: 25
      <<: *Telefonos
      title: _("List of %s", ngettext('Teléfono', 'Teléfonos', 0))
      class: ui-silk-phone
      filterField: contribuyenteId
      parentOptionCustomizer:
        - recordCount
      fields:
        options:
          title: _("Options")
          screens:
            telefonosEdit_screen: true
          dialogs:
            telefonosDel_dialog: true
          default: telefonosEdit_screen
      options:
        title: _("Options")
        screens:
          telefonosNew_screen: true
        dialogs:
          telefonosDel_dialog: true
          
    telefonosNew_screen: &telefonosNew_screenLink 
      <<: *Telefonos
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Teléfono', 'Teléfonos', 1))
      filterField: contribuyenteId
      fields:
        blacklist:
          createdOn: true
    telefonosEdit_screen: &telefonosEdit_screenLink 
      <<: *Telefonos
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Teléfono', 'Teléfonos', 1))
      filterField: contribuyenteId
      fields:
        blacklist:
          createdOn: true
  dialogs: 
    telefonosDel_dialog: &telefonosDel_dialogLink 
      <<: *Telefonos
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Telefono', 'Telefonos', 1))
      description: _("Do you want to delete this %s?", ngettext('Telefono', 'Telefonos', 1))
      message: _("%s successfully deleted.", ngettext('Telefono', 'Telefonos', 1))
      multiItem: 1
      labelOnList: 1
      
    telefonosAddDel_dialog: &telefonosAddDel_dialogLink 
      <<: *Telefonos
      module: default
      controller: klear-contribuyente-telefono
      action: index
      label: true
      class: ui-silk-phone-add
      title: _("Agregar teléfono", '%parent%')
      description: _("Se añadirá un número de teléfono al contribuyente al que se está editando.")
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
