#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: tiposIncidenciasList_screen
  screens: 
    tiposIncidenciasList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *TiposIncidencias
      title: _("List of %s", ngettext('Tipos incidencia', 'Tipos incidencias', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            tiposIncidenciasEdit_screen: true
          dialogs: 
            tiposIncidenciasDel_dialog: true
          default: tiposIncidenciasEdit_screen
        blacklist:
          plantillasEmailId: true
          plantillasEmailPrioridad: true
          plantillasSmsId: true
          plantillasSmsPrioridad: true
          plantillasTelefonoId: true
          plantillasTelefonoPrioridad: true
      options: 
        title: _("Options")
        screens: 
          tiposIncidenciasNew_screen: true
    tiposIncidenciasNew_screen: 
      <<: *TiposIncidencias
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Tipos incidencia', 'Tipos incidencias', 1))
      fields:
        order:
          gravedad: true
          tipo: true
          descripcion: true
          resolucionAutomatica: true
          plantillasEmailPrioridad: true
          plantillasEmailId: true
          plantillasSmsPrioridad: true
          plantillasSmsId: true
          plantillasTelefonoPrioridad: true
          plantillasTelefonoId: true
      fixedPositions:
        group0:
          label: _('Email');
          fields:
            plantillasEmailPrioridad: true
            plantillasEmailId: true
        group1:
          label: _('Sms');
          fields:
            plantillasSmsPrioridad: true
            plantillasSmsId: true
        group2:
          label: _('Teléfono');
          fields:
            plantillasTelefonoPrioridad: true
            plantillasTelefonoId: true
    tiposIncidenciasEdit_screen: 
      <<: *TiposIncidencias
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Tipos incidencia', 'Tipos incidencias', 1))
      fields:
        order:
          gravedad: true
          tipo: true
          descripcion: true
          resolucionAutomatica: true
          plantillasEmailPrioridad: true
          plantillasEmailId: true
          plantillasSmsPrioridad: true
          plantillasSmsId: true
          plantillasTelefonoPrioridad: true
          plantillasTelefonoId: true
      fixedPositions:
        group0:
          label: _('Email');
          fields:
            plantillasEmailPrioridad: true
            plantillasEmailId: true
        group1:
          label: _('Sms');
          fields:
            plantillasSmsPrioridad: true
            plantillasSmsId: true
        group2:
          label: _('Teléfono');
          fields:
            plantillasTelefonoPrioridad: true
            plantillasTelefonoId: true
  dialogs: 
    tiposIncidenciasDel_dialog: 
      <<: *TiposIncidencias
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Tipos incidencia', 'Tipos incidencias', 1))
      description: _("Do you want to delete this %s?", ngettext('Tipos incidencia', 'Tipos incidencias', 1))
testing: 
  _extends: production
development: 
  _extends: production
