#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: turnosCamionesRelOperariosList_screen
  screens: 
    turnosCamionesRelOperariosList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *TurnosCamionesRelOperarios
      title: _("List of %s", ngettext('Turnos camiones rel operario', 'Turnos camiones rel operarios', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            turnosCamionesRelOperariosEdit_screen: true
          dialogs: 
            turnosCamionesRelOperariosDel_dialog: true
          default: turnosCamionesRelOperariosEdit_screen
      options: 
        title: _("Options")
        screens: 
          turnosCamionesRelOperariosNew_screen: true
    turnosCamionesRelOperariosNew_screen: 
      <<: *TurnosCamionesRelOperarios
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Turnos camiones rel operario', 'Turnos camiones rel operarios', 1))
    turnosCamionesRelOperariosEdit_screen: 
      <<: *TurnosCamionesRelOperarios
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Turnos camiones rel operario', 'Turnos camiones rel operarios', 1))
  dialogs: 
    turnosCamionesRelOperariosDel_dialog: 
      <<: *TurnosCamionesRelOperarios
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Turnos camiones rel operario', 'Turnos camiones rel operarios', 1))
      description: _("Do you want to delete this %s?", ngettext('Turnos camiones rel operario', 'Turnos camiones rel operarios', 1))
testing: 
  _extends: production
development: 
  _extends: production
