#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: turnosList_screen
  screens: 
    turnosList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *Turnos
      title: _("List of %s", ngettext('Turno', 'Turnos', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            turnosEdit_screen: true
            operariosRelTurnoList_screen: false
          dialogs: 
            turnosDel_dialog: true
          default: turnosEdit_screen
      options: 
        title: _("Options")
        screens: 
          turnosNew_screen: true
    turnosNew_screen: 
      <<: *Turnos
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Turno', 'Turnos', 1))
    turnosEdit_screen: 
      <<: *Turnos
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Turno', 'Turnos', 1))
      
    operariosRelTurnoList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *OperariosRelTurno
      title: _("List of %s", ngettext('Operario', 'Operarios', 0))
      filterField: turnoId
      class: ui-silk-group-add
      fields: 
        options: 
          title: _("Options")
          screens: 
            operariosRelTurnoEdit_screen: false
          dialogs: 
            operariosRelTurnoDel_dialog: true
          default: operariosRelTurnoEdit_screen
      options: 
        title: _("Options")
        screens: 
          operariosRelTurnoNew_screen: true
    operariosRelTurnoNew_screen: 
      <<: *OperariosRelTurno
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Operarios rel turno', 'Operarios rel turno(s)', 1))
      filterField: turnoId
    operariosRelTurnoEdit_screen: 
      <<: *OperariosRelTurno
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Operarios rel turno', 'Operarios rel turno(s)', 1))
      filterField: turnoId
      
  dialogs: 
    turnosDel_dialog: 
      <<: *Turnos
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Turno', 'Turnos', 1))
      description: _("Do you want to delete this %s?", ngettext('Turno', 'Turnos', 1))
      
    operariosRelTurnoDel_dialog: 
      <<: *OperariosRelTurno
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Operarios rel turno', 'Operarios rel turno(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Operarios rel turno', 'Operarios rel turno(s)', 1))
testing: 
  _extends: production
development: 
  _extends: production
