#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: turnosRelCamionesList_screen
  screens: 
    turnosRelCamionesList_screen: 
      controller: list
      pagination: 
        items: 25
      <<: *TurnosRelCamiones
      title: _("List of %s", ngettext('Camión', 'Camiones', 0))
      fields: 
        options: 
          title: _("Options")
          screens: 
            turnosRelCamionesEdit_screen: true
          dialogs: 
            turnosRelCamionesDel_dialog: true
          default: turnosRelCamionesEdit_screen
      options: 
        title: _("Options")
        screens: 
          turnosRelCamionesNew_screen: true
    turnosRelCamionesNew_screen: 
      <<: *TurnosRelCamiones
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Camión', 'Camiones', 1))
    turnosRelCamionesEdit_screen: 
      <<: *TurnosRelCamiones
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s", ngettext('Camión', 'Camiones', 1))
  dialogs: 
    turnosRelCamionesDel_dialog: 
      <<: *TurnosRelCamiones
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Camión', 'Camiones', 1))
      description: _("Do you want to delete this %s?", ngettext('Camión', 'Camiones', 1))
testing: 
  _extends: production
development: 
  _extends: production
