mappers: 
  - &Camiones {mapper: \Atezate\Mapper\Sql\Camiones, modelFile: Camiones}
  - &CentrosEmergencia {mapper: \Atezate\Mapper\Sql\CentrosEmergencia, modelFile: CentrosEmergencia}
  - &CodigoApertura {mapper: \Atezate\Mapper\Sql\CodigoApertura, modelFile: CodigoApertura}
  - &CodigosApertura {mapper: \Atezate\Mapper\Sql\CodigosApertura, modelFile: CodigosApertura}
  - &CodigosAperturaPrivados {mapper: \Atezate\Mapper\Sql\CodigosAperturaPrivados, modelFile: CodigosAperturaPrivados}
  - &CodigosPostales {mapper: \Atezate\Mapper\Sql\CodigosPostales, modelFile: CodigosPostales}
  - &Compostadores {mapper: \Atezate\Mapper\Sql\Compostadores, modelFile: Compostadores}
  - &CompostadoresRelContribuyentes {mapper: \Atezate\Mapper\Sql\CompostadoresRelContribuyentes, modelFile: CompostadoresRelContribuyentes}
  - &Contribuyentes {mapper: \Atezate\Mapper\Sql\Contribuyentes, modelFile: Contribuyentes}
  - &Cubos {mapper: \Atezate\Mapper\Sql\Cubos, modelFile: Cubos}
  - &CubosImportadores {mapper: \Atezate\Mapper\Sql\CubosImportadores, modelFile: CubosImportadores}
  - &CubosTipos {mapper: \Atezate\Mapper\Sql\CubosTipos, modelFile: CubosTipos}
  - &Descargas {mapper: \Atezate\Mapper\Sql\Descargas, modelFile: Descargas}
  - &Dispositivos {mapper: \Atezate\Mapper\Sql\Dispositivos, modelFile: Dispositivos}
  - &Emails {mapper: \Atezate\Mapper\Sql\Emails, modelFile: Emails}
  - &FileAccess {mapper: \Atezate\Mapper\Sql\FileAccess, modelFile: FileAccess}
  - &Importadores {mapper: \Atezate\Mapper\Sql\Importadores, modelFile: Importadores}
  - &Incidencias {mapper: \Atezate\Mapper\Sql\Incidencias, modelFile: Incidencias}
  - &KlearRoles {mapper: \Atezate\Mapper\Sql\KlearRoles, modelFile: KlearRoles}
  - &KlearRolesSections {mapper: \Atezate\Mapper\Sql\KlearRolesSections, modelFile: KlearRolesSections}
  - &KlearSections {mapper: \Atezate\Mapper\Sql\KlearSections, modelFile: KlearSections}
  - &KlearUsers {mapper: \Atezate\Mapper\Sql\KlearUsers, modelFile: KlearUsers}
  - &KlearUsersRoles {mapper: \Atezate\Mapper\Sql\KlearUsersRoles, modelFile: KlearUsersRoles}
  - &Locuciones {mapper: \Atezate\Mapper\Sql\Locuciones, modelFile: Locuciones}
  - &LogEmails {mapper: \Atezate\Mapper\Sql\LogEmails, modelFile: LogEmails}
  - &LogLlamadas {mapper: \Atezate\Mapper\Sql\LogLlamadas, modelFile: LogLlamadas}
  - &LogSms {mapper: \Atezate\Mapper\Sql\LogSms, modelFile: LogSms}
  - &MarcasCompostador {mapper: \Atezate\Mapper\Sql\MarcasCompostador, modelFile: MarcasCompostador}
  - &MarcasCubo {mapper: \Atezate\Mapper\Sql\MarcasCubo, modelFile: MarcasCubo}
  - &MarcasDispositivo {mapper: \Atezate\Mapper\Sql\MarcasDispositivo, modelFile: MarcasDispositivo}
  - &MarcasPoste {mapper: \Atezate\Mapper\Sql\MarcasPoste, modelFile: MarcasPoste}
  - &Municipios {mapper: \Atezate\Mapper\Sql\Municipios, modelFile: Municipios}
  - &MunicipiosRelCercania {mapper: \Atezate\Mapper\Sql\MunicipiosRelCercania, modelFile: MunicipiosRelCercania}
  - &MunicipiosRelCodigosPostales {mapper: \Atezate\Mapper\Sql\MunicipiosRelCodigosPostales, modelFile: MunicipiosRelCodigosPostales}
  - &Operarios {mapper: \Atezate\Mapper\Sql\Operarios, modelFile: Operarios}
  - &Paradas {mapper: \Atezate\Mapper\Sql\Paradas, modelFile: Paradas}
  - &PlantillasEmail {mapper: \Atezate\Mapper\Sql\PlantillasEmail, modelFile: PlantillasEmail}
  - &PlantillasSms {mapper: \Atezate\Mapper\Sql\PlantillasSms, modelFile: PlantillasSms}
  - &PlantillasTelefono {mapper: \Atezate\Mapper\Sql\PlantillasTelefono, modelFile: PlantillasTelefono}
  - &Posicionamiento {mapper: \Atezate\Mapper\Sql\Posicionamiento, modelFile: Posicionamiento}
  - &Postes {mapper: \Atezate\Mapper\Sql\Postes, modelFile: Postes}
  - &PostesTipos {mapper: \Atezate\Mapper\Sql\PostesTipos, modelFile: PostesTipos}
  - &PuntosDescarga {mapper: \Atezate\Mapper\Sql\PuntosDescarga, modelFile: PuntosDescarga}
  - &PuntosRecogida {mapper: \Atezate\Mapper\Sql\PuntosRecogida, modelFile: PuntosRecogida}
  - &PuntosRecogidaTipos {mapper: \Atezate\Mapper\Sql\PuntosRecogidaTipos, modelFile: PuntosRecogidaTipos}
  - &RecogidaTipos {mapper: \Atezate\Mapper\Sql\RecogidaTipos, modelFile: RecogidaTipos}
  - &Recogidas {mapper: \Atezate\Mapper\Sql\Recogidas, modelFile: Recogidas}
  - &ResiduosTipos {mapper: \Atezate\Mapper\Sql\ResiduosTipos, modelFile: ResiduosTipos}
  - &Revision {mapper: \Atezate\Mapper\Sql\Revision, modelFile: Revision}
  - &RevisionTipos {mapper: \Atezate\Mapper\Sql\RevisionTipos, modelFile: RevisionTipos}
  - &Roles {mapper: \Atezate\Mapper\Sql\Roles, modelFile: Roles}
  - &Rutas {mapper: \Atezate\Mapper\Sql\Rutas, modelFile: Rutas}
  - &RutasRelPuntosRecogida {mapper: \Atezate\Mapper\Sql\RutasRelPuntosRecogida, modelFile: RutasRelPuntosRecogida}
  - &RutasTipos {mapper: \Atezate\Mapper\Sql\RutasTipos, modelFile: RutasTipos}
  - &Telefonos {mapper: \Atezate\Mapper\Sql\Telefonos, modelFile: Telefonos}
  - &TiposIncidencias {mapper: \Atezate\Mapper\Sql\TiposIncidencias, modelFile: TiposIncidencias}
  - &Turnos {mapper: \Atezate\Mapper\Sql\Turnos, modelFile: Turnos}
  - &TurnosCamionesRelOperarios {mapper: \Atezate\Mapper\Sql\TurnosCamionesRelOperarios, modelFile: TurnosCamionesRelOperarios}
  - &TurnosRelCamiones {mapper: \Atezate\Mapper\Sql\TurnosRelCamiones, modelFile: TurnosRelCamiones}
