production: 
  class: \Atezate\Model\CodigoApertura
  fields: 
    centroEmergenciaId: 
      title: _('Centro emergencia')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Atezate\Mapper\Sql\CentrosEmergencia
          fieldName: 
            fields: 
              - ip
            template: '%ip%'
          order: ip
      default: true
    fechaVencimiento: 
      title: _('Fecha vencimiento')
      type: picker
      required: true
      source: 
        control: date
        settings: 
          disabled: 'false'
    codigo: 
      title: _('Codigo')
      type: text
      required: true
    contribuyenteId: 
      title: _('Contribuyente NIF')
      type: select
      source: 
        data: mapper
        'null': _("Unasigned")
        config: 
          mapperName: \Atezate\Mapper\Sql\Contribuyentes
          fieldName: 
            fields: 
              - nif
            template: '%nif%'
          order: nif
    createdOn: 
      title: _('Created on')
      type: picker
      defaultValue: CURRENT_TIMESTAMP
      source: 
        control: datetime
        settings: 
          disabled: 'false'
    grabado: 
      title: _('Grabado')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
testing: 
  _extends: production
development: 
  _extends: production
