production: 
  class: \Atezate\Model\Descargas
  fields: 
    camionId: 
      title: _('Camion')
      type: select
      source: 
        data: mapper
        'null': _("Unasigned")
        config: 
          mapperName: \Atezate\Mapper\Sql\Camiones
          fieldName: 
            fields: 
              - matricula
            template: '%matricula%'
          order: matricula
      default: true
    puntoDescargaId: 
      title: _('Punto descarga')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Atezate\Mapper\Sql\PuntosDescarga
          fieldName: 
            fields: 
              - puntosDescargaIden
            template: '%puntosDescargaIden%'
          order: puntosDescargaIden
    kilos: 
      title: _('Kilo')
      type: number
      required: true
      source: 
        control: Spinner
    createdOn: 
      title: _('Created on')
      type: picker
      defaultValue: CURRENT_TIMESTAMP
      source: 
        control: datetime
        settings: 
          disabled: 'false'
testing: 
  _extends: production
development: 
  _extends: production
