production: 
  class: \Atezate\Model\LogEmails
  fields: 
    asunto: 
      title: _('Asunto')
      type: text
      required: true
      default: true
    mensaje: 
      title: _('Mensaje')
      type: textarea
    createdOn: 
      title: _('Created on')
      type: picker
      defaultValue: CURRENT_TIMESTAMP
      source: 
        control: datetime
        settings: 
          disabled: 'false'
    incidenciaId: 
      title: _('Incidencia')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Atezate\Mapper\Sql\Incidencias
          fieldName: 
            fields: 
              - incidenciaId
            template: '%incidenciaId%'
          order: incidenciaId
testing: 
  _extends: production
development: 
  _extends: production
