production: 
  class: \Atezate\Model\Paradas
  fields: 
    turnosCamionesId: 
      title: _('Turnos camiones')
      type: select
      source: 
        data: mapper
        'null': _("Unasigned")
        config: 
          mapperName: \Atezate\Mapper\Sql\TurnosRelCamiones
          fieldName: 
            fields: 
              - id
            template: '%id%'
          order: id
      default: true
    horaInicio: 
      title: _('Hora inicio')
      type: picker
      required: true
      source: 
        control: time
        settings: 
          disabled: 'false'
    finalizado: 
      title: _('Finalizado')
      type: select
      defaultValue: 0
      source: 
        data: inline
        values: 
          '0': 
            title: _("No")
          '1': 
            title: _("Yes")
    horaFinal: 
      title: _('Hora final')
      type: picker
      source: 
        control: time
        settings: 
          disabled: 'false'
    puntosRecogidasId: 
      title: _('Puntos recogidas')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Atezate\Mapper\Sql\PuntosRecogida
          fieldName: 
            fields: 
              - nombreDescriptivo
            template: '%nombreDescriptivo%'
          order: nombreDescriptivo
          filterClass: Atezatelib_Filtros_FilterPuntosRecogidaByParadas
    createdOn: 
      title: _('Created on')
      type: picker
      defaultValue: CURRENT_TIMESTAMP
      source: 
        control: datetime
        settings: 
          disabled: 'false'
testing: 
  _extends: production
development: 
  _extends: production
