production: 
  class: \Atezate\Model\Posicionamiento
  fields: 
    turnosCamionesId: 
      title: _('Turnos camiones')
      type: select
      source: 
        data: mapper
        'null': _("Unasigned")
        config: 
          mapperName: \Atezate\Mapper\Sql\TurnosRelCamiones
          fieldName: 
            fields: 
              - id
            template: '%id%'
          order: id
      default: true
    precision: 
      title: _('Precision')
      type: text
    fecha: 
      title: _('Fecha')
      type: picker
      required: true
      source: 
        control: datetime
        settings: 
          disabled: 'false'
    createdOn: 
      title: _('Created on')
      type: picker
      defaultValue: CURRENT_TIMESTAMP
      source: 
        control: datetime
        settings: 
          disabled: 'false'
    posicion: 
      title: _('Posicion')
      type: textarea
testing: 
  _extends: production
development: 
  _extends: production
