production: 
  class: \Atezate\Model\PuntosRecogidaTipos
  fields: 
    nombre: 
      title: _('Nombre')
      type: text
      required: true
      default: true
    descripcion: 
      title: _('Descripcion')
      type: textarea
testing: 
  _extends: production
development: 
  _extends: production
